default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: calendar_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: calendar_production
  username: calendar
  password: <%= ENV["CALENDAR_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
